### ISSUE TITLE
Add and fix Python 3.7

### ISSUE THREAD

**Issue by hugovk** [whyaretheflagsup/whyaretheflagsup.github.io#16]
https://travis-ci.org/whyaretheflagsup/whyaretheflagsup.github.io/builds/453262179

Fails with:
```
0.22s$ python whyaretheflagsup.py --test -y whyaretheflagsup_example.yaml -i flag.jpg
Saturday, 10. November 2018 01:16PM whyaretheflagsup.py
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/opt/python/3.7.1/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/opt/python/3.7.1/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'phantomjs': 'phantomjs'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "whyaretheflagsup.py", line 169, in <module>
    reason = flag_reason()
  File "whyaretheflagsup.py", line 34, in flag_reason
    driver = webdriver.PhantomJS(service_log_path=os.path.devnull)  # headless
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 56, in __init__
    self.service.start()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH. 
The command "python whyaretheflagsup.py --test -y whyaretheflagsup_example.yaml -i flag.jpg" exited with 1.
```

Might be fixed by #15.

**Comment by hugovk** [comment]
Twitter and Travis are no longer important.
